repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: go-vet

-   repo: local
    hooks:
    -   id: go-unit-tests
        name: go unit tests
        entry: bash -c 'set -e; FILES=$(go list ./... | grep -v /vendor/); go test -tags=unit -timeout 30s -short -v ${FILES}'
        pass_filenames: false
        types: [go]
        language: system
