General:
  debugEnabled: false # if true, debug messages will be shown during init. Different from log level
  silenceConfigWarnings: false # if true, no warnings will be shown for missing or incorrect configuration values
  logLevel: "debug" # The log level that will be used for the application. Possible values are: "trace", "debug", "info", "warn", "error", "fatal", "panic"

File:
  # The path to the target file. The file should be in the xlsx format.
  targetFilePath: "./ebase.xlsx"
  # The name of the sheet in the file that will be used for the upload. If the sheet name is not provided, a sheet with the yyyy-MM-dd format of the first day of this week.
  targetSheetName: ""
  #TO ADD
  templateSheetName: "Template" # Name of the empty, but formatted sheet used to create new ones

Project:
  # The default project name that will be used for the upload.
  defaultProjectName: "CS0126444 - Wonen Cloudzone - dedicated operationeel projectteam"

JiraRef:
  # The default value for the Jira reference field.
  defaultValue: "OPS-305"
  # Whether the default value should be set for the Jira reference field.
  setDefaultValue: true

AppRef:
  # The default value for the Application reference field.
  defaultValue: ""
  # Whether the default value should be set for the Application reference field.
  setDefaultValue: false
