General:
  # if true, debug messages will be shown during init. Different from log level. Leave on false unless you're experiencing issues.
  debugEnabled: false
  # if true, no warnings will be shown for missing or incorrect configuration values. Set it to false to see warnings.
  silenceConfigWarnings: true
  # The log level that will be used for the application. Possible values are: "trace", "debug", "info", "warn", "error", "fatal", "panic"
  # Default value is "info". Set it to "debug" for verbose output if you're having issues.
  logLevel: "debug"

File:
  # The path to the target xlsx file. If the file does not exist, it will be created.
  # If it's an existing sheet - this can be used to support supplying a custom-formatted template file.
  targetFilePath: "./ebase3.xlsx"
  #targetFilePath: "/Users/wvannuffelen/wvl/devel/tempo/timsheet (version 2) (version 2) (version 2) (version 1)(AutoRecovered) OK-2024(AutoRecovered).xlsx"
  # The name of the sheet in the file that will be used. If the sheet name is not provided, a sheet with the yyyy-MM-dd format of the first day of this week.
  targetSheetName: ""
  # If set to false, sheets will be created from scratch instead of using a user-formatted template sheet.
  useTemplateSheet: false
  # Name of the empty, but user formatted sheet used to create new ones. If empty, the first sheet in the target file will be used.
  templateSheetName: "Template"

Project:
  # The default project name that will be used for timesheet entry or keyword creation.
  defaultProjectName: "CS0126444 - Wonen Cloudzone - dedicated operationeel projectteam"

JiraRef:
  # The default value for the Jira reference field.
  defaultValue: "OPS-305"
  # Whether the default value should be set for the Jira reference field.
  setDefaultValue: true
  # Whether the default value should be set for the Jira reference field when creating new keywords.
  setDefaultValueForNewKeywords: true

AppRef:
  # The default value for the Application reference field.
  defaultValue: ""
  # Whether the default value should be set for the Application reference field.
  setDefaultValue: false
  # Whether the default value should be set for the Application reference field when creating new keywords.
  setDefaultValueForNewKeywords: false

Keywords:
  # Default output type: json or pp (pretty print)
  defaultOutputFormat: "pp"

ShowTimeSheetEntry:
  # Default output type: json or pp (pretty print)
  defaultOutputFormat: "json"
  # Hide Project from output of tse show command?
  hideProject: false
  # Hide JiraRef from output of tse show command?
  hideJiraRef: false
  # Hide AppRef from output of tse show command?
  hideAppRef: false
